language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - rbx-2
  - jruby
  - ruby-head
  - jruby-head
before_install: gem install bundler -v 1.10.6
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
addons:
  code_climate:
    repo_token: 3967a141e0a4910cba7c8b82d2dab094939483528ef42a9ab57ea4fdc50f4716
